/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.test.app;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.test.list.LinkedList;

import static org.test.utilities.StringUtils.join;
import static org.test.utilities.StringUtils.split;
import static org.test.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {

    private static final Logger LOGGER = LogManager.getLogger();

    public static void main(String[] args) {
        LOGGER.info("starting...");
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        LOGGER.info(WordUtils.capitalize(result));
    }
}
