/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.test.app;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

class MessageUtils {

    private static final Logger LOGGER = LogManager.getLogger();


    public static String getMessage() {
        LOGGER.info("getMessage invoked");
        return "Hello      World!";
    }
}
